// In-memory mock database
function generateId() {
  return Date.now().toString() + Math.random().toString(36).substr(2, 9);
}

export const mockDb = {
  tasks: [
    {
      id: '1',
      title: 'Complete Physics Lab Report',
      subject: 'Physics',
      deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'High' as const,
      status: 'pending',
      source: 'Manual',
      ai_summary: 'Complete the pendulum experiment lab report including calculations and error analysis.',
      steps: [
        { label: 'Gather experimental data', done: true },
        { label: 'Perform calculations', done: false },
        { label: 'Write conclusion', done: false },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'Study for Math Midterm',
      subject: 'Mathematics',
      deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'High' as const,
      status: 'pending',
      source: 'Manual',
      ai_summary: 'Review chapters 5-8 covering calculus and derivatives.',
      steps: [
        { label: 'Review lecture notes', done: false },
        { label: 'Practice problems', done: false },
        { label: 'Take practice exam', done: false },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '3',
      title: 'Chemistry Problem Set',
      subject: 'Chemistry',
      deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'Medium' as const,
      status: 'pending',
      source: 'Manual',
      ai_summary: 'Complete problem set on chemical equilibrium and Le Chatelier principle.',
      steps: [
        { label: 'Read chapter 14', done: true },
        { label: 'Complete problems 1-10', done: false },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '4',
      title: 'English Essay Draft',
      subject: 'English',
      deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'Medium' as const,
      status: 'pending',
      source: 'Manual',
      ai_summary: 'Write first draft of analytical essay on Shakespearean sonnets.',
      steps: [
        { label: 'Research sources', done: true },
        { label: 'Create outline', done: true },
        { label: 'Write introduction', done: false },
        { label: 'Write body paragraphs', done: false },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '5',
      title: 'Prepare Presentation',
      subject: 'History',
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'Low' as const,
      status: 'pending',
      source: 'Manual',
      ai_summary: 'Create PowerPoint presentation on World War II.',
      steps: [
        { label: 'Research topic', done: false },
        { label: 'Design slides', done: false },
        { label: 'Practice delivery', done: false },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  inboxItems: [
    {
      id: 'inbox1',
      kind: 'Manual' as const,
      status: 'New' as const,
      extracted: 'Review biology chapter 7 before tomorrow',
      original_text: 'Review biology chapter 7 before tomorrow',
      file_path: null,
      task_id: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'inbox2',
      kind: 'Manual' as const,
      status: 'Processed' as const,
      extracted: 'Group project meeting at 3pm',
      original_text: 'Group project meeting at 3pm',
      file_path: null,
      task_id: null,
      created_at: new Date().toISOString(),
    },
  ],
  voiceNotes: [
    {
      id: 'voice1',
      transcript: 'Remember to submit the economics assignment by Friday evening',
      duration: 5,
      file_path: '/uploads/demo.webm',
      processed: true,
      task_id: null,
      created_at: new Date().toISOString(),
    },
  ],
};
